/* eslint-disable react/prop-types */
import './globals.css'
import { Inter } from 'next/font/google'
import React from 'react'
import Navbar from '@/components/navbar/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang="es">
      <body style={{ width: '100vw', height: '100vh', display: 'flex', flexDirection: 'column' }} className={inter.className}>
        <nav style={{ width: '100%', height: '10%' }} > <Navbar/></nav>
        <main style={{ width: '100%', height: '80%' }} className='bg-gray-100'>
          {children}
        </main>
      </body>
    </html>
  )
}
